[font]
"A" = [0, 0]
"B" = [1, 0]
"C" = [2, 0]
"D" = [3, 0]
"E" = [4, 0]
"F" = [5, 0]
"G" = [6, 0]
"H" = [7, 0]
"I" = [0, 1]
"J" = [1, 1]
"K" = [2, 1]
"L" = [3, 1]
"M" = [4, 1]
"N" = [5, 1]
"O" = [6, 1]
"P" = [7, 1]
"Q" = [0, 2]
"R" = [1, 2]
"S" = [2, 2]
"T" = [3, 2]
"U" = [4, 2]
"V" = [5, 2]
"W" = [6, 2]
"X" = [7, 2]
"Y" = [0, 3]
"Z" = [1, 3]
"a" = [0, 0]
"b" = [1, 0]
"c" = [2, 0]
"d" = [3, 0]
"e" = [4, 0]
"f" = [5, 0]
"g" = [6, 0]
"h" = [7, 0]
"i" = [0, 1]
"j" = [1, 1]
"k" = [2, 1]
"l" = [3, 1]
"m" = [4, 1]
"n" = [5, 1]
"o" = [6, 1]
"p" = [7, 1]
"q" = [0, 2]
"r" = [1, 2]
"s" = [2, 2]
"t" = [3, 2]
"u" = [4, 2]
"v" = [5, 2]
"w" = [6, 2]
"x" = [7, 2]
"y" = [0, 3]
"z" = [1, 3]
"0" = [2, 3]
"1" = [3, 3]
"2" = [4, 3]
"3" = [5, 3]
"4" = [6, 3]
"5" = [7, 3]
"6" = [0, 4]
"7" = [1, 4]
"8" = [2, 4]
"9" = [3, 4]
" " = [4, 4]
"!" = [5, 4]
"?" = [6, 4]
":" = [7, 4]
";" = [0, 5]
"." = [1, 5]
"," = [2, 5]
"/" = [3, 5]
"%" = [4, 5]
"$" = [5, 5]
"(" = [6, 5]
")" = [7, 5]
"+" = [0, 6]
"-" = [1, 6]
"=" = [2, 6]
"*" = [3, 6]
"'" = [4, 6]
"\"" = [5, 6]
"\\" = [6, 6]
"&" = [7, 6]
"А" = [0, 0]
"Б" = [0, 7]
"В" = [1, 0]
"Г" = [1, 7]
"Д" = [2, 7]
"Е" = [4, 0]
"Ё" = [3, 7]
"Ж" = [4, 7]
"З" = [5, 3]
"И" = [5, 7]
"Й" = [6, 7]
"К" = [2, 1]
"Л" = [7, 7]
"М" = [4, 1]
"Н" = [5, 1]
"О" = [6, 1]
"П" = [0, 8]
"Р" = [7, 1]
"С" = [2, 0]
"Т" = [3, 2]
"У" = [0, 3]
"Ф" = [1, 8]
"Х" = [7, 2]
"Ц" = [2, 8]
"Ч" = [3, 8]
"Ш" = [4, 8]
"Щ" = [5, 8]
"Ъ" = [6, 8]
"Ы" = [7, 8]
"Ь" = [0, 9]
"Э" = [1, 9]
"Ю" = [2, 9]
"Я" = [3, 9]
"а" = [0, 0]
"б" = [0, 7]
"в" = [1, 0]
"г" = [1, 7]
"д" = [2, 7]
"е" = [4, 0]
"ё" = [3, 7]
"ж" = [4, 7]
"з" = [5, 3]
"и" = [5, 7]
"й" = [6, 7]
"к" = [2, 1]
"л" = [7, 7]
"м" = [4, 1]
"н" = [5, 1]
"о" = [6, 1]
"п" = [0, 8]
"р" = [7, 1]
"с" = [2, 0]
"т" = [3, 2]
"у" = [0, 3]
"ф" = [1, 8]
"х" = [7, 2]
"ц" = [2, 8]
"ч" = [3, 8]
"ш" = [4, 8]
"щ" = [5, 8]
"ъ" = [6, 8]
"ы" = [7, 8]
"ь" = [0, 9]
"э" = [1, 9]
"ю" = [2, 9]
"я" = [3, 9]
"{" = [4, 9]
"}" = [5, 9]
"<" = [6, 9]
">" = [7, 9]
"[" = [0, 10]
"]" = [1, 10]
"#" = [2, 10]
"@" = [3, 10]
"~" = [4, 10]
"|" = [5, 10]
