name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.build-type }} build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build-type: [dev, release]
        os: [
            windows-latest,
#           macOS-latest,
            ubuntu-latest
        ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up nightly Rust
      run: |
           rustup toolchain add nightly
           rustup default nightly

    - name: Install ninja (Windows)
      if: matrix.os == "windows-latest"
      run: choco install ninja

    - name: Install ninja (Linux)
      if: matrix.os == "ubuntu-latest"
      run: |
        sudo apt update 
        sudo apt install -y ninja-build

    - name: Build
      run: cargo build --profile ${{ matrix.build-type }} --verbose --out-dir out -Z unstable-options
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: false_king-${{ matrix.build-type }}-${{ matrix.os }}
        path: out